//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceCodePBL3.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatMonAn
    {
        public string MaMonAn { get; set; }
        public string MaBanAn { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> TongTien { get; set; }
    
        public virtual BanAn BanAn { get; set; }
        public virtual MonAn MonAn { get; set; }
    }
}
