//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceCodePBL3.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public string MaHoaDon { get; set; }
        public string MaBanAn { get; set; }
        public System.DateTime NgayThanhToan { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public string MaNhanVienOrder { get; set; }
        public Nullable<bool> TrangThaiTT { get; set; }
        public string HinhThucTT { get; set; }
    
        public virtual BanAn BanAn { get; set; }
        public virtual ThanhVien ThanhVien { get; set; }
    }
}
