//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceCodePBL3.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonAn
    {
        public string MaLoaiMonAn { get; set; }
        public string MaMonAn { get; set; }
        public string TenMonAn { get; set; }
        public Nullable<decimal> GiaTien { get; set; }
    
        public virtual DatMonAn DatMonAn { get; set; }
        public virtual Kho Kho { get; set; }
        public virtual LoaiMonAn LoaiMonAn { get; set; }
    }
}
